language: cpp
compiler: gcc
dist: trusty

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty
  - llvm-toolchain-trusty-4.0
  - llvm-toolchain-trusty-5.0
  - llvm-toolchain-trusty-6.0

addons:
  apt:
    sources: *all_sources
    packages:
    - python3
    - python3-pip
    - g++-8

install: 
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  # we use wget to fetch the cmake binaries
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.14/cmake-3.14.2-Linux-x86_64.tar.gz
  # extract the binaries; the output here is quite lengthy,
  # so we swallow it to not clutter up the travis console
  - tar -xvf cmake-3.14.2-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.14.2-Linux-x86_64 cmake-install
  # add both the top-level directory and the bin directory from the archive
  # to the system PATH. By adding it to the front of the path we hide the
  # preinstalled CMake with our own.
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  # don't forget to switch back to the main build directory once you are done
  - cd ${TRAVIS_BUILD_DIR}
  - pip install conan --user
  #- sudo apt-get install -qq g++-8 cmake
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90

script: 
  - conan remote add comunity https://api.bintray.com/conan/conan-community/conan 
  - conan remote list
  - git submodule update --init 
  - mkdir build
  - cd build
  - cmake --version
  - conan install .. --build boost -s compiler=gcc -s compiler.version=8
  - cmake ..
  - make -j 2
  - CTEST_OUTPUT_ON_FAILURE=1 ctest -C Debug .  --verbose
